export enum TransactionType {
  ISSUE = 'ISS',
  TRANSFER_IN = 'TRN_IN',
  TRANSFER_OUT = 'TRN_OUT',
  RECEIVE = 'REV',
  RECEIVE_OTHER = 'REV_OTHER',
  REQUISITION_IN = 'REQ_IN',
  REQUISITION_OUT = 'REQ_OUT',
  ISSUE_TRANSACTION = 'IST',
  ADJUST = 'ADJUST',
  HIS = 'HIS',
  ADDITION_IN = 'ADD_IN',
  ADDITION_OUT = 'ADD_OUT',
  RETURNED = 'RTN',
  BORROW_IN = 'BORROW_IN',
  BORROW_OUT = 'BORROW_OUT'
}